services:
  app:
    image: mks050/ims:latest
    ports:
      - "${APP_HOSTS_PORT}:8080"
    env_file:
      - .env
    volumes:
      - h2-data:/opt/h2-data
    networks:
      - my-network

volumes:
  h2-data:

networks:
  my-network:
